import Head from 'next/head'
import { Header } from '@component/component/header/header'
import { Base } from '@component/component/home/Home'
import { About } from '@component/component/about/About'
import { Skills } from '@component/component/skills/Skills'
import { Portfolio } from '@component/component/portfolio/Portfolio'
import { Qualification } from '@component/component/qualification/Qualification'

export default function Home() {
  return (
    <>
      <Head>
        <title>Jose Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css" />
      </Head>
      <Header />
      <main className='main'>
        <Base />
        <About />
        <Qualification />
        <Skills />
        <Portfolio />
      </main>
    </>
  )
}
